# Generated by Django 2.1.5 on 2019-08-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(null=True, to='crm.Role'),
        ),
    ]
