# Generated by Django 2.1.5 on 2019-08-03 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20190802_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'verbose_name': '客户信息', 'verbose_name_plural': '客户信息'},
        ),
    ]
