# Generated by Django 2.1.5 on 2019-08-03 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190803_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={},
        ),
    ]
